### ISSUE TITLE
Feature request: -v or --version option for all tools

### ISSUE THREAD

**Issue by jsmif** [whad-team/whad-client#49]
A --version CLI argument for tools would probably save you headache long-term when trying to confirm which version of tools people are experiencing issues with. (Or to ask people to confirm they're up to date with the latest.)

**Comment by virtualabs** [comment]
I've added a generic `--version` option to our CLI tool wrapper, any tool will report the framework version if `--version` option is passed in argument. 

This modification has been pushed in `dev` branch, you can checkout and test it.

**Comment by virtualabs** [comment]
Allright, closing this one.
