### ISSUE TITLE
"ble-wireshark" vs "wshark" update

### ISSUE THREAD

**Issue by jsmif** [whad-team/whad-client#51]
There are 3 references to "ble-wireshark" which should probably be references to "wshark"?

https://github.com/search?q=repo%3Awhad-team%2Fwhad-client%20%22ble-wireshark%22&type=code

I only noticed because I was using the instructions from https://whad.readthedocs.io/en/stable/cli/ble/ble-spawn.html and it complained that there's no "ble-wireshark". I went to see if I could make a simple documentation fix, but while a fix to "[doc/source/cli/ble/ble-spawn.rst](https://github.com/whad-team/whad-client/blob/909b4af17959cac04e21aca5eeb21e6b319da246/doc/source/cli/ble/ble-spawn.rst#L36)" looks easy enough, it's not clear to me how to fix the other 2 references, so I figured it's better if you do it.

**Comment by virtualabs** [comment]
You nailed it, we started writing the documentation months ago and decided at some point to rename our tools to follow a common pattern. And obviously forgot to change the tool name in some documentation pages :pensive:.

**Comment by virtualabs** [comment]
Removed old references to `ble-wireshark` and fixed other typos in different CLI tools' doc pages.
